import Settings from './src/settings';

export default {
  gitlab: {
    url: 'https://bitbox.plateforme-2cloud.com',
    token: process.env.GITLAB_TOKEN,
    projectId: Number(process.argv[2]),
    sessionCookie: process.env.GITLAB_SESSION,
  },
  github: {
    // baseUrl: 'https://github.mycompany.com:123/etc',
    // apiUrl: 'https//api.github.mycompany.com',
    owner: 'ubitransports',
    token: process.env.GITHUB_TOKEN,
    token_owner: process.env.GITHUB_TOKEN_OWNER,
    repo: process.argv[3],
    recreateRepo: false,
  },
  //s3: {
  //  accessKeyId: '{{accessKeyId}}',
  //  secretAccessKey: '{{secretAccessKey}}',
  //  bucket: 'my-gitlab-bucket',
  //},
  usermap: {
    'dpedreno': 'dpedreno-ubitransport',
    'cislam': 'cislam-ubitransport',
    'sbarboyo': 'sbarboyon-ext',
    'slemoigne': 'slemoigne',
    'xfroelicher': 'xfroelicher',
    'bdimitrov': 'bdimitrov-ubitransport',
    'cbruyere': 'Cbruyere',
    'gnikolov': 'GeorgiNikolovUbi',
    'cdemazure': 'colinedemazureubitransport',
    'kmartins': 'KevinMartinsDev',
    'kkaramazov': 'kkaramazov-ubitransport',
    'afrancois': 'afrancois-ubitransport',
    'everneret': 'everneret',
    'mpadellini': 'mpadelliniOpRate',
    'nroman': 'nroman-ext',
    'sholo': 's-holo',
    'thenon': 'thomas-henon',
    'aschelch': 'aschelch',
    'bmartin': 'bjmmartin',
    'jretornaz': 'jretornaz',
    'ppichet': 'p-pichet',
    'yivanov': 'yivanov-ubitransport',
    'fismailov': 'fismailov-ubitransport',
    'nfierimonte': 'nfierimonte',
    'vdanti': 'vincentdnt',
    'yhelin': 'yhelin',
    'Xiipiou': 'ubi-adumont',
    'hcombe': 'hcombe',
  },
  projectmap: {
    // 'gitlabgroup/projectname.1': 'GitHubOrg/projectname.1',
    // 'gitlabgroup/projectname.2': 'GitHubOrg/projectname.2',
  },
  conversion: {
    useLowerCaseLabels: true,
  },
  transfer: {
    description: true,
    milestones: true,
    labels: true,
    issues: false,
    mergeRequests: true,
    releases: true,
  },
  debug: false,
  useIssueImportAPI: true,
  usePlaceholderMilestonesForMissingMilestones: true,
  usePlaceholderIssuesForMissingIssues: true,
  useReplacementIssuesForCreationFails: true,
  useIssuesForAllMergeRequests: false,
  filterByLabel: null,
  skipMergeRequestStates: [],
  skipMatchingComments: [],
  mergeRequests: {
    logFile: './merge-requests.json',
    log: false,
  },
} as Settings;

